//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrompirApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KrompirDatabaseEntities : DbContext
    {
        public KrompirDatabaseEntities()
            : base("name=KrompirDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DNEVNIK_PARCELE> DNEVNIK_PARCELE { get; set; }
        public virtual DbSet<ETIKETA> ETIKETA { get; set; }
        public virtual DbSet<KOLICINA_PROIZVEDENOG_KROMPIRA> KOLICINA_PROIZVEDENOG_KROMPIRA { get; set; }
        public virtual DbSet<PRINOS_PARCELE> PRINOS_PARCELE { get; set; }
        public virtual DbSet<PROIZVODJAC> PROIZVODJAC { get; set; }
        public virtual DbSet<SIFRA_SORTE> SIFRA_SORTE { get; set; }
        public virtual DbSet<UNOS_U_DNEVNIK> UNOS_U_DNEVNIK { get; set; }
        public virtual DbSet<PARCELA> PARCELA { get; set; }
    }
}
