//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrompirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARCELA()
        {
            this.DNEVNIK_PARCELE = new HashSet<DNEVNIK_PARCELE>();
            this.PRINOS_PARCELE = new HashSet<PRINOS_PARCELE>();
        }
    
        public int PARCELAID { get; set; }
        public Nullable<int> PROIZVODJACID { get; set; }
        public string MJESTO { get; set; }
        public string KATASTARSKAOPSTINA { get; set; }
        public string KCBROJ { get; set; }
        public Nullable<int> POVRSINA { get; set; }
        public string PREDUSJEV { get; set; }
        public string SORTAID { get; set; }
        public string POSADJENAKATEGORIJASADNOGMATERIJALA { get; set; }
        public Nullable<System.DateTime> DATUMSADNJE { get; set; }
        public Nullable<int> POSADJENAKOLICINA { get; set; }
        public bool DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNEVNIK_PARCELE> DNEVNIK_PARCELE { get; set; }
        public virtual PROIZVODJAC PROIZVODJAC { get; set; }
        public virtual SIFRA_SORTE SIFRA_SORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRINOS_PARCELE> PRINOS_PARCELE { get; set; }
    }
}
