//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrompirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINOS_PARCELE
    {
        public int PRINOSID { get; set; }
        public Nullable<int> PROIZVEDENAKOLICINA { get; set; }
        public Nullable<int> PARCELAID { get; set; }
        public bool DELETED { get; set; }
    
        public virtual PARCELA PARCELA { get; set; }
    }
}
