//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrompirApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROIZVODJAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROIZVODJAC()
        {
            this.ETIKETA = new HashSet<ETIKETA>();
            this.KOLICINA_PROIZVEDENOG_KROMPIRA = new HashSet<KOLICINA_PROIZVEDENOG_KROMPIRA>();
            this.PARCELA = new HashSet<PARCELA>();
        }
    
        public int PROIZVODJACID { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public Nullable<System.DateTime> DATUMRODJENJA { get; set; }
        public string MJESTOSTANOVANJA { get; set; }
        public string ADRESA { get; set; }
        public string APIF { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public bool DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETIKETA> ETIKETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOLICINA_PROIZVEDENOG_KROMPIRA> KOLICINA_PROIZVEDENOG_KROMPIRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCELA> PARCELA { get; set; }
    }
}
